### ISSUE TITLE
github.Repo.create_release does not set target_commitish

### ISSUE THREAD

**Issue by papr** [jaraco/jaraco.develop#3]
The problem: If one creates a tag on a _non-default_ branch and uses the `jaraco/skeleton` then `python -m jaraco.develop.create-github-release` will create a new `v`-prefixed tag on the default branch which will not match the original branch.

To solve this issue, one could set the [`target_commitish` parameter of the `/releases` API call](https://docs.github.com/en/rest/releases/releases#create-a-release).

**Comment by jaraco** [comment]
Thanks for reporting the issue. According to the docs for `target_commitish`:

> Unused if the Git tag already exists. 

In my workflows, I typically push the tag to the repo prior to running the release workflow, so even if the tag were on a non-default branch, Github would not create a new tag. In fact, it's usually the push of the tag that triggers the release.

Maybe it would make sense to specify the current commitish, but then that would [trigger another release](https://github.com/jaraco/skeleton/blob/54675240d4b4d2452a3777c5156f688e42a6c985/.github/workflows/main.yml#L80-L83), only to fail because the release has already been uploaded, so that doesn't feel like an adequate solution.

Is there a reason your workflow doesn't do something similar?

**Comment by papr** [comment]
Hey, thanks for looking into this!

I use the tag to trigger the workflow, too. But the difference might be that I don't prefix my tags with `v`.

**Comment by jaraco** [comment]
Can you illustrate what you're proposing with a patch?

**Comment by jaraco** [comment]
Closing as it's a little stale. Feel free to revive the conversation.
